<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="bethmi" name="com.test.ng.EmployeeServiceImplTest" tests="2" failures="1" timestamp="17 Sep 2018 08:21:00 GMT" time="0.031" errors="0">
  <testcase name="testGenerateBasicSalaryGeneratedException" time="0.001" classname="com.test.ng.EmployeeServiceImplTest">
    <failure type="org.testng.TestException" message="
Expected exception java.lang.Exception but got org.testng.TestException: 
The exception was thrown with the wrong message: expected &quot;Employee working details canno&quot; but got &quot;Employee working details cannot be null&quot;">
      <![CDATA[org.testng.TestException: 
Expected exception java.lang.Exception but got org.testng.TestException: 
The exception was thrown with the wrong message: expected "Employee working details canno" but got "Employee working details cannot be null"
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1497)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1245)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: org.testng.TestException: 
The exception was thrown with the wrong message: expected "Employee working details canno" but got "Employee working details cannot be null"
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1481)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:754)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	... 22 more
Caused by: java.lang.Exception: Employee working details cannot be null
	at com.test.ng.service.impl.EmployeeServiceImpl.generateBasicSalary(EmployeeServiceImpl.java:28)
	at com.test.ng.EmployeeServiceImplTest.testGenerateBasicSalaryGeneratedException(EmployeeServiceImplTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	... 24 more
]]>
    </failure>
  </testcase> <!-- testGenerateBasicSalaryGeneratedException -->
  <testcase name="testGenerateBasicSalaryFailure" time="0.030" classname="com.test.ng.EmployeeServiceImplTest"/>
</testsuite> <!-- com.test.ng.EmployeeServiceImplTest -->
